### ISSUE TITLE
File input

### ISSUE THREAD

**Issue by WillemJan** [impactcentre/iif-taverna2-client#2]
Currently the input supported are Strings and URL's. We would like to upload files, the code to do this is already there, we should re-enable this.

**Comment by reinouts** [comment]
When I click the input switch icon, in Firebug I see the following error:

SecurityError: The operation is insecure.
http://succeed.kbresearch.nl/dp/WorkflowParser
Line 34

if(oldObject.value) newObject.value = oldObject.value;

**Comment by reinouts** [comment]
The javascript tries to set the value property of the file input field, which is illegal. This can only be done by the user.
